version: '3'
services:
  client:
    restart: always
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
  api:
    restart: always
    build: ./api
    ports:
    - '5050:5050'
